export default {
    login: "login",
    register: "register",
    logout: 'logout',
    myFavourites: 'my-favourite',
    getBowls: 'get-bowls',
    getSauces: 'get-sauces',
    getChefCurated: 'get-chef-curated',
    myOrders: 'my-orders',
    myAddressList: 'get-addresses',
    getPastas: 'get-pastas',
    getGarnishes: 'get-garnishes',
    getMeats: 'get-meats',
    getSides: 'get-sides',
    addToCart: 'add-to-cart',
    getVeggies: 'get-vegetables',
    getCartItems: 'get-cart-items',
    getExtras: 'get-extras',
    updateCartItemQuantity: 'update-cart-quantity',
    getOrderDetails: 'order-details',
    deleteCartItem: 'delete-cart-item',
    storePayment: 'store-payment',
    saveOrder: 'save-order',
    getCoupons: 'get-coupons',
    checkCoupon: 'check-coupon',
    orderDetails: 'order-details',
    reorder: 'reorder',
    addAddress: 'add-address',
    verifyOtp: 'confirm-account',
    getStaticPage: 'get-page-details',
    updateCartItem :'update-cart-item',
    resendOtp: 'send-otp',
    getKitchen: 'get-kitchen',
    getCities: 'cities',
    getLocations: 'locations',
    forgotPassword: 'forgot-password'

}